import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — FirePath",
  description: "FirePath Terms of Service. By using FirePath you agree to these terms.",
};

const EFFECTIVE_DATE = "February 28, 2026";

export default function TermsPage(): React.JSX.Element {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 py-12">
      <h1 className="font-display text-4xl font-bold mb-2">Terms of Service</h1>
      <p className="text-muted-foreground text-sm mb-10">Effective date: {EFFECTIVE_DATE}</p>

      <div className="prose prose-sm max-w-none space-y-10 text-sm text-foreground leading-relaxed">

        {/* 1 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By accessing or using FirePath (the &quot;Service&quot;), you agree to be bound by these
            Terms of Service (&quot;Terms&quot;). If you do not agree to all of these Terms, do not use
            the Service. These Terms apply to all visitors and users of the Service.
          </p>
        </section>

        {/* 2 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">2. Description of Service</h2>
          <p className="text-muted-foreground">
            FirePath is a free, browser-based financial planning tool designed for educational and
            informational purposes. It provides calculators, projections, and simulations related to
            the concept of Financial Independence, Retire Early (&quot;FIRE&quot;). All calculations
            run entirely in your browser; no financial data is transmitted to or stored on our servers
            except as described in our Privacy Policy.
          </p>
        </section>

        {/* 3 — most important */}
        <section className="rounded-xl border-2 border-destructive/40 bg-destructive/5 p-6">
          <h2 className="text-lg font-semibold mb-3 text-destructive">
            3. Not Financial, Tax, or Legal Advice
          </h2>
          <div className="space-y-3 text-muted-foreground">
            <p>
              <strong className="text-foreground">FirePath is not a registered investment adviser,
              broker-dealer, financial planner, tax adviser, or legal professional.</strong> Nothing
              on this Service constitutes financial advice, investment advice, tax advice, accounting
              advice, or legal advice of any kind.
            </p>
            <p>
              All projections, simulations, estimates, and outputs generated by FirePath are
              <strong className="text-foreground"> hypothetical and for illustrative purposes only</strong>.
              They are based on mathematical models, user-supplied inputs, and historical data that
              may not be accurate, complete, or applicable to your individual situation.
            </p>
            <p>
              <strong className="text-foreground">Past market performance does not guarantee future
              results.</strong> Actual investment returns, tax obligations, Social Security benefits,
              healthcare costs, and other financial outcomes may differ materially from any
              projections shown.
            </p>
            <p>
              Before making any financial, investment, tax, or retirement decisions, you should
              consult a qualified and licensed professional — such as a certified financial planner
              (CFP), registered investment adviser (RIA), certified public accountant (CPA), or
              attorney — who can evaluate your specific circumstances.
            </p>
          </div>
        </section>

        {/* 4 */}
        <section className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-lg font-semibold mb-3">
            4. Disclaimer of Warranties
          </h2>
          <div className="space-y-3 text-muted-foreground">
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTY
              OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OR
              NON-INFRINGEMENT.
            </p>
            <p>
              We do not warrant that: (a) the Service will be uninterrupted, error-free, or secure;
              (b) the results or calculations obtained from the Service will be accurate or reliable;
              (c) any errors in the Service will be corrected; or (d) the Service will meet your
              requirements.
            </p>
            <p>
              Calculation results — including but not limited to FIRE numbers, years to retirement,
              Monte Carlo success rates, Social Security benefit estimates, tax projections, Roth
              conversion amounts, and healthcare cost estimates — are approximations based on
              simplified models and historical data. They should not be relied upon as precise
              forecasts.
            </p>
          </div>
        </section>

        {/* 5 */}
        <section className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-lg font-semibold mb-3">
            5. Limitation of Liability
          </h2>
          <div className="space-y-3 text-muted-foreground">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL FIREPATH, ITS
              OWNERS, OPERATORS, CONTRIBUTORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR DAMAGES FOR LOSS OF PROFITS,
              REVENUE, DATA, BUSINESS, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR
              RELATED TO YOUR USE OF (OR INABILITY TO USE) THE SERVICE, EVEN IF ADVISED OF THE
              POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>
              THIS INCLUDES, WITHOUT LIMITATION, ANY DAMAGES ARISING FROM: (a) FINANCIAL DECISIONS
              MADE IN RELIANCE ON OUTPUTS FROM THE SERVICE; (b) ERRORS OR INACCURACIES IN
              CALCULATIONS; (c) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA; OR (d) ANY OTHER
              MATTER RELATING TO THE SERVICE.
            </p>
            <p>
              IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, OUR
              LIABILITY SHALL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.
            </p>
          </div>
        </section>

        {/* 6 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">6. Accuracy of Information</h2>
          <p className="text-muted-foreground">
            Tax brackets, Social Security bend points, ACA premium data, Medicare premiums, and other
            regulatory figures embedded in this Service reflect data available at the time of
            development and may not reflect the most current figures. Tax law, Social Security rules,
            and healthcare regulations change frequently. Always verify current figures with official
            government sources (IRS.gov, SSA.gov, HealthCare.gov, CMS.gov) or a qualified
            professional before acting on any estimate from this Service.
          </p>
        </section>

        {/* 7 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">7. User Responsibilities</h2>
          <p className="text-muted-foreground">
            You are solely responsible for: (a) verifying the accuracy of any inputs you provide;
            (b) independently verifying any outputs before making financial decisions; (c) complying
            with all applicable laws and regulations in your jurisdiction; and (d) seeking
            professional advice appropriate to your circumstances.
          </p>
        </section>

        {/* 8 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">8. Intellectual Property</h2>
          <p className="text-muted-foreground">
            The Service and its original content, features, and functionality are owned by FirePath
            and are protected by copyright and other intellectual property laws. You may use the
            Service for personal, non-commercial purposes only.
          </p>
        </section>

        {/* 9 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">9. Third-Party Services</h2>
          <p className="text-muted-foreground">
            The optional AI Insights feature sends anonymized financial parameters (no personal
            identifiers) to Anthropic&apos;s Claude API. Your use of this feature is also subject to
            Anthropic&apos;s terms of service and privacy policy. FirePath is not responsible for the
            content, accuracy, or availability of third-party services.
          </p>
        </section>

        {/* 10 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">10. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify these Terms at any time. We will update the effective date
            at the top of this page. Your continued use of the Service after any changes constitutes
            acceptance of the revised Terms.
          </p>
        </section>

        {/* 11 */}
        <section>
          <h2 className="text-lg font-semibold mb-3">11. Severability</h2>
          <p className="text-muted-foreground">
            If any provision of these Terms is found to be unenforceable or invalid, that provision
            shall be limited or eliminated to the minimum extent necessary so that these Terms shall
            otherwise remain in full force and effect.
          </p>
        </section>

        <div className="rounded-lg border border-border bg-card p-4 text-xs text-muted-foreground">
          <strong className="text-foreground">Note:</strong> These Terms of Service were last updated
          on {EFFECTIVE_DATE}. For questions, consult the{" "}
          <a href="/about" className="underline hover:text-foreground">methodology page</a> or review
          our <a href="/privacy" className="underline hover:text-foreground">Privacy Policy</a>.
        </div>
      </div>
    </div>
  );
}
